---Insert da tabela PERFIL---
INSERT  INTO PERFIL(DESCRICAO, ROLE) VALUES ('USER','ROLE_USER'); 
INSERT  INTO PERFIL(DESCRICAO, ROLE) VALUES ('ADMINISTRADOR','ROLE_ADMIN');

---Insert da tabela STATUS---
INSERT  INTO STATUS(DESCRICAO) VALUES ('Criada');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Solicitada');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Avaliada para Execução');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Avaliada para Aprecicação do Comitê');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Avaliada para Nova Versão');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Submetida');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Em Análise');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Aguardando Aprovação do usuário');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Em execução');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Em Teste');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Em Homologação');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Aguardando Liberação');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Aguardando Finalização');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Finalizadas');
INSERT  INTO STATUS(DESCRICAO) VALUES ('Canceladas e Suspensas');

---Insert da tabela CLASSIFICACAO---
INSERT  INTO CLASSIFICACAO(DESCRICAO) VALUES ('Melhoria de Sistema');
INSERT  INTO CLASSIFICACAO(DESCRICAO) VALUES ('Manutenção Corretiva');
INSERT  INTO CLASSIFICACAO(DESCRICAO) VALUES ('Manutenção Preventiva');
INSERT  INTO CLASSIFICACAO(DESCRICAO) VALUES ('Mudança de Metodologia');
INSERT  INTO CLASSIFICACAO(DESCRICAO) VALUES ('Outros');

--Criação dos Tipo Demanda---
INSERT  INTO TIPO_DEMANDA(DESCRICAO) VALUES ('CSD');
INSERT  INTO TIPO_DEMANDA(DESCRICAO) VALUES ('Interna');